import { Connection } from "@solana/web3.js";
import { getOrca, Network, OrcaPoolConfig } from "@orca-so/sdk";
import Decimal from "decimal.js";

const RPC_ENDPOINT_URL = "https://api.devnet.solana.com";
const commitment = 'confirmed';
const connection = new Connection(RPC_ENDPOINT_URL, commitment);

// Phantom dummy for TS
declare global { interface Window { solana: any; } }

async function main() {
    // connect to phantom
    let wallet_pubkey = null;
    try {
        const resp = await window.solana.connect();
        wallet_pubkey = resp.publicKey;
    } catch (err) {
        console.log(err.message);
        return;
    }

    // setting
    const orca = getOrca(connection, Network.DEVNET);
    const orca_sol_pool = orca.getPool(OrcaPoolConfig.ORCA_SOL);
    const sol_token = orca_sol_pool.getTokenB();
    const sol_amount = new Decimal(0.0005);

    // get quote
    const quote = await orca_sol_pool.getQuote(sol_token, sol_amount);
    const usdc_amount = quote.getMinOutputAmount();
    console.log(`Swap ${sol_amount.toString()} SOL for at least ${usdc_amount.toNumber()} ORCA`);

    // sign by temporary account generated by SDK
    const payload = await orca_sol_pool.swap(wallet_pubkey, sol_token, sol_amount, usdc_amount);
    const transaction = payload.transaction;
    transaction.partialSign(...payload.signers);
    console.log("partialSign!");

    // sign and send transaction by Phantom
    // using signAndSendTransaction, "-32003 Transaction creation failed." error occurred.
    // const { signature } = await window.solana.signAndSendTransaction(transaction);
    const signed_transaction = await window.solana.signTransaction(transaction);
    console.log("sign by Phantom!");
    const signature = await connection.sendRawTransaction(signed_transaction.serialize());

    await connection.confirmTransaction(signature);
    console.log(`Swapped: ${signature}`);
    window.alert(signature);
}

main();

// SAMPLE TX: https://solscan.io/tx/a6hkAT1AFKtoBLbVsjFcZV2VUkUkC1kGsbgfjjvaUAPfCvXH3c746wstnxNzxhiaCGQPCKWHyrRxVaHpBw8D8Xt?cluster=devnet
//
// PACKAGING: browserify src/main.ts -p tsify > bundle.js
//
// MEMO: ORCAの sdk と aquafarm が内包している spl-token の package.json のなかの下記の記述を変えないと下記のエラーが起きる (cjs用がない...)
//
// [BEFORE]
// "browser": {
//    "./lib/index.cjs.js": "./lib/index.browser.esm.js",
//    "./lib/index.esm.js": "./lib/index.browser.esm.js"
//  },
//
// [AFTER]
//  "browser": {
//    "./lib/index.cjs.js": "./lib/index.cjs.js",
//    "./lib/index.esm.js": "./lib/index.esm.js"
//  },
//
// SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0) while parsing node_modules/@solana/spl-token/lib/index.browser.esm.js
// while parsing file: node_modules/@solana/spl-token/lib/index.browser.esm.js
